version: 1
accounts:
  - name: user1
    coins: ["1000token", "1000000000stake"]
  - name: user2
    coins: ["500token"]
validator:
  name: user1
  staked: "100000000stake"
genesis:
  app_state:
    mint:
      params:
        inflation_max: "0.000000000000000000"
        inflation_min: "0.000000000000000000"
    gravity:
      params:
        gravity_id: "cudos-gravity-test"
