version: '3.1'

networks:
  shared-cudos-network:
    external:
      name: shared-cudos-network

volumes:
  node-01-data:
    driver: local
  node-02-data:
    driver: local
  # cudos-root_data:
  #   external: true
  #   name: cudos-root_data

services:
  cudos-node-01:
    image: cudos-node-01
    container_name: cudos-node-01
    # environment:
      # - MONIKER=cudos-node-01
      # - PERSISTENT_NODE_ID=29d18d4505e234b376689c54de68f07bc6138421@cudos-root-node:26656
    build:
      dockerfile: docker/network.dockerfile
      context: ../
      args:
        - MONIKER=cudos-node-01
      #   - PERSISTENT_NODE_ID=29d18d4505e234b376689c54de68f07bc6138421@cudos-root-node:26656
    restart: unless-stopped
    volumes:
      # - 'cudos-root_data:/usr/cudos-root'
      - 'node-01-data:/usr/cudos/cudos-data'
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
    networks:
      - shared-cudos-network

  cudos-node-02:
    image: cudos-node-02
    container_name: cudos-node-02
    # environment:
      # - MONIKER=cudos-node-02
    build:
      dockerfile: docker/network.dockerfile
      context: ../
      args:
        - MONIKER=cudos-node-02
    restart: unless-stopped
    volumes:
      # - 'cudos-root_data:/usr/cudos-root'
      - 'node-02-data:/usr/cudos/cudos-data'
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
    networks:
      - shared-cudos-network