version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

volumes:
  data:
    driver: local
   
services:
  cudos-root-node:
    image: cudos-root-node
    container_name: cudos-root-node
    build:
      dockerfile: docker/root-node.dockerfile
      context: ../
    restart: unless-stopped
    volumes:
      - 'data:/usr/cudos/cudos-data'
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    networks:
      - shared-cudos-network