version: '3.1'

networks:
  shared-cudos-network:
    external:
      name: shared-cudos-network

volumes:
  explorer-mongodbdata:
    driver: local

services:
  cudos-explorer:
    image: cudos-explorer
    container_name: cudos-explorer
    build:
      dockerfile: docker/utils-explorer.dockerfile
      context: ../
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5000:5000"
    networks:
      - shared-cudos-network

  cudos-explorer-mongodb:
    image: 'mongo:latest'
    container_name: cudos-explorer-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cudos-root-db-pass
    volumes:
      - 'explorer-mongodbdata:/data/db'
      - './config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
    networks:
      - shared-cudos-network

  cudos-faucet-cli:
    image: cudos-faucet-cli
    container_name: cudos-faucet-cli
    build:
      dockerfile: docker/utils-faucet-cli.dockerfile
      context: ../
    restart: unless-stopped
    networks:
      - shared-cudos-network